import smtplib
from email.message import EmailMessage
from dotenv import load_dotenv
import os

from screenshot import take_screenshots

load_dotenv()


def send_email(results):
    msg = EmailMessage()

    msg["Subject"] = "Job Screenshot Report"
    msg["From"] = os.getenv("EMAIL")
    msg["To"] = os.getenv("RECEIVER_EMAIL")

  

    body = "JOB SCRAPING REPORT\n"
   
    body += "SUCCESSFUL JOBS:\n\n"

    success_count = 0
    failed_count = 0

    for r in results:
        if r["status"] == "success":
            success_count += 1
            body += f"✔ {r['url']}\n"

    body += "\nFAILED JOBS:\n\n"

    for r in results:
        if r["status"] == "failed":
            failed_count += 1
            body += f"✖ {r['url']}\n"
            body += f"   Reason: {r['error']}\n\n"

    
    body += f"Summary: {success_count} success, {failed_count} failed\n"
    body += "Generated by Job Agent \n"

    msg.set_content(body)


    for r in results:
        if r["status"] == "success":
            with open(r["file"], "rb") as f:
                msg.add_attachment(
                    f.read(),
                    maintype="image",
                    subtype="png",
                    filename=r["file"]
                )

    

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(os.getenv("EMAIL"), os.getenv("APP_PASSWORD"))
        smtp.send_message(msg)